name: portfoliodev

on:
  push:
    branches:
      main

permissions:
    contents: read
    pages: write
    id-token: write  

jobs:
  deploy_portfolio:
    runs-on: ubuntu:latest

    steps:
      - name: checkout code 
        uses: actions/checkout@v5

      - name: setuppages 
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4


